### ISSUE TITLE
Heads up; PHP7 nightly

### ISSUE THREAD

**Issue by olssonm** [bjeavons/zxcvbn-php#17]
Hi! I'm using your package as a dependency for [olssonm/l5-zxcvbn](https://github.com/olssonm/l5-zxcvbn).

I just updated it to include v0.2.0 and some other fixes. When I ran the tests in Travis upon the PR, I noticed that zxcvbn-php caused an error in PHP 7 nightly. Older versions (including PHP 7) passed flawlessly.

Now, I haven't found anything that indicates that the nightly version has changed anything on how arrays in strings are handled, might just be a bug in the nightly version that will be patched later on. Just thought that I should give you a heads up if this causes any issues in the future.

The error is thrown at https://github.com/bjeavons/zxcvbn-php/blob/master/src/Matchers/L33tMatch.php#L55

The error:
`Error: [] operator not supported for strings`

See https://travis-ci.org/olssonm/l5-zxcvbn/jobs/173946497 for the complete test suite.

Keep up the good work!

**Comment by sstok** [comment]
`"{$password[$i]} -> $t"` this should do the trick 👍

**Comment by fcfidel** [comment]
nope still says:

**Fatal error: Uncaught Error: [] operator not supported for strings **
