### ISSUE TITLE
PHP 7.1.3: error "[] operator not supported for strings"

### ISSUE THREAD

**Issue by ctoesca** [bjeavons/zxcvbn-php#24]
Since PHP 7.1.3: this code doesn't work:

```
$zxcvbn = new Zxcvbn();
$strength = $zxcvbn->passwordStrength("secret");
```

Error message: **"[] operator not supported for strings"**

Trace: 
bjeavons\\zxcvbn-php\\src\\ZxcvbnPhp\\Matchers\\L33tMatch.php:55
bjeavons\\zxcvbn-php\\src\\ZxcvbnPhp\\Matcher.php:27
bjeavons\\zxcvbn-php\\src\\ZxcvbnPhp\\Zxcvbn.php:53

**Comment by ctoesca** [comment]
Correction:
ZxcvbnPhp\Matchers\L33tMatch.php:52 :

`$result['sub_display'] = '';  `
replaced by:
`$result['sub_display'] = [];`

**Comment by bjeavons** [comment]
https://github.com/bjeavons/zxcvbn-php/commit/7a7e1130c74c715e84c60c27384f657e9574a933 corrected this
