### ISSUE TITLE
Why match_sequence gives back an Object not an Array?

### ISSUE THREAD

**Issue by hamburger123456** [bjeavons/zxcvbn-php#26]
match_sequence!=Array 

```
$zxcvbn = new Zxcvbn();
$strength = $zxcvbn->passwordStrength('asdf', $userData);
echo "score_1 : ".$strength['score'].RT;
// will print 0
echo RT.RT;var_dump($strength); echo RT.RT;
```

gives:

 `array(6) { ["crack_time"]=> float(0.00865) ["calc_time"]=> float(0.0287201404572) ["password"]=> string(4) "asdf" ["entropy"]=> float(7.43462822764) ["match_sequence"]=> array(1) { [0]=> object(ZxcvbnPhp\Matchers\DictionaryMatch)#7 (10) { ["dictionaryName"]=> string(9) "passwords" ["rank"]=> int(173) ["matchedWord"]=> string(4) "asdf" ["password"]=> string(4) "asdf" ["begin"]=> int(0) ["end"]=> int(3) ["token"]=> string(4) "asdf" ["pattern"]=> string(10) "dictionary" ["entropy"]=> NULL ["cardinality"]=> NULL } } ["score"]=> int(0) } `

**Comment by mkopinsky** [comment]
I'm not sure what you're saying here. In the output you pasted, `match_sequence` is an array of Match objects.
