### ISSUE TITLE
Documentation request!

### ISSUE THREAD

**Issue by Saeven** [bjeavons/zxcvbn-php#40]
Not a dealbreaker - but It'd be helpful if the readme identified the upper and lower range for score, or how to apply best practices to interpreting the result that the check provides.

Neat lib though, thank you!

**Comment by bjeavons** [comment]
Hi @Saeven, good suggestion, thank you. We can copy from https://github.com/dropbox/zxcvbn/blob/master/README.md#usage to achieve that.
