### ISSUE TITLE
PHP 8 syntax error, unexpected token "match"

### ISSUE THREAD

**Issue by AnnoyingTechnology** [bjeavons/zxcvbn-php#46]
There is a conflict with a new PHP8 reserved word [`match`](https://www.php.net/match)
`bjeavons/zxcvbn-php/src/Matchers/DateMatch.php`

**Comment by jdreesen** [comment]
Actually it should be its parent class `ZxcvbnPhp\Matchers\Match`, whose name is not allowed anymore with PHP 8.

**Comment by mkopinsky** [comment]
Thanks for the report!
